### PR TITLE
Removed restriction on fixed bind appendix and RDN. 

### PR DESCRIPTION
**Pull request by chhu**
Before attempting bind, a search is made with a custom bind user for a record that has mail=query.email. Once found, the full dn is extracted and another LDAP bind is performed to that DN with provided password.
Great work! Thanks!

### CODE REVIEW

**Comment by smhaller** [comment]
Thx, I'll merge it a soon as i did a run on my test instance (later this week)

**Comment by haslersn** [comment]
Please don't replace uid lookup by mail lookup. Also, user input should be escaped. I suggest e.g. [this patch](https://github.com/SF2311/ldap-overleaf-sl/compare/53a4ba6b4f95499c1d1350ea8e4b9ab41e611552..34614356c9d0a2b9e216b8c47de3245035f07156).

**Comment by smhaller** [comment]
I wont replace it - i might merge it in such a way that this is configurable from the docker-compose file

**Comment by chhu** [comment]
The ldap escape is a great idea, I would implement that. The prefix for the search can be configurable with another env with a default to "uid=" (or mail?).

**Comment by chhu** [comment]
Hmm the e-mail split to uid seems to be a very specific use-case that requires your mail user name to be equal to the uid in ldap. Also it does not care or check what comes after the @. Not very generic...

**Comment by smhaller** [comment]
> Hmm the e-mail split to uid seems to be a very specific use-case that requires your mail user name to be equal to the uid in ldap. Also it does not care or check what comes after the @. Not very generic...

Not really - sharelatex normally uses the email address as login. i wanted that the uid is checked against ldap and the email login against the mongodb. In the query you get query.email (which might be an email or uid)... i just check if the first part is the uid (with the split and bind) - Note: if there is no @ symbol you get the whole string.

**Comment by smhaller** [comment]
Small Note: This happens after a check to the local database. So uid and first part of email can be different (and most likely are)

**Comment by haslersn** [comment]
I think it would be clever to require the UID without `@example.com` suffix. That is, simply set:

```
var uid = query.email
```

This way, even UIDs containing an `@` are allowed.

**Comment by haslersn** [comment]
@chhu As a first step, please merge in the commits I linked ([this patch](https://github.com/SF2311/ldap-overleaf-sl/compare/53a4ba6b4f95499c1d1350ea8e4b9ab41e611552..34614356c9d0a2b9e216b8c47de3245035f07156)). An then merge smhaller/master to resolve conflicts. We can proceed from there.

**Comment by smhaller** [comment]
@haslersn: I am not sure if it is wise to allow symbols like @ or : in uids. You might open a door to hell ;) - the first 2 things which come to my mind are:
 - it might be confusing with emails
 - you get troubles if you want to use your ldap for e.g. unix authentication/authorisation

**Comment by chhu** [comment]
So I implemented the ldap-escape and the missing client.unbind. To not confuse our users I left the filter to mail. We actually changed our ldap to have uid==mail. Users register with different email domains with us and we dont want to confuse them because some services require email and others uid to login. The split from the uid would prevent that and other services (like rocketchat) use the mail field to login too. Just reject the pull if it does not fit your requirements. However, big thanks for the initial work!

**Comment by smhaller** [comment]
This is was solved with pull request #9. And is already merged.

**Pull request closed without merging**
