### PR TITLE
Sync to latest version & improvements

### PR DESCRIPTION
**Pull request by dingyx99**
* Create a network in the Makefile, no need to create network manually
* Sync to the latest sharelatex (currently it's 3.0.1), fix errors when building images
* Make `tlmgr` works, validated by myself

### CODE REVIEW

**Comment by christf** [comment]
I am not the maintainer of the project. I do not think however the make file that is meant to build the image should also manage the run-time aspects of the container including managing the network.

**Comment by smhaller** [comment]
I agree with @christf .

**Comment by christf** [comment]
well, besides the network config there were other changes in this PR that look useful. Maybe re-raising those separately would be helpful?

**Comment by smhaller** [comment]
There were not many modifications. We should not put sharelatex:latest because on version switches one sometimes has to adapt the authentication file - and the main branch should be a working one (see Issue #7). The automated network creation we keep outside the Makefile.
Latest commit contains the tab fixes (Makefile) and the comment on share.pug (Dockerfile)

**Pull request closed without merging**
